### ISSUE TITLE
MCP23S17/MCP23017 missing two input bit of the 16Bit Chip

### ISSUE THREAD

**Issue by dev-markus** [wollewald/MCP23017_WE#25]
Problem with follow Chips:
* MCP23S17
* MCP23017

when one of the pins (GPA7 or GPB7) are high there will output a strange result:

  correct output:
  00000000 00000000 (all pins are connected to a other input source at low)
  01000000 00000000 (one input are high, correct result)

  not correct result:  
  0000000 00000000  (one bit are missing from bank A or B)
  
why does the output show results where a 1/0 is missing?

Code:

```
#include <SPI.h>
#include <MCP23S17.h>
#define CS_PIN 7   
#define RESET_PIN 5 
#define MCP_ADDRESS 0x20

MCP23S17 myMCP = MCP23S17(CS_PIN, RESET_PIN, MCP_ADDRESS);


int wT = 500;
byte portStatusA;
byte portStatusB;


void setup(){ 
 
  Serial.begin(9600);
  SPI.begin();

  if(!myMCP.Init()){
    Serial.println("Not connected!");
    while(1){} 
  }
 
  Serial.println("CHIP: ready");
  delay(wT);

  myMCP.setPortMode(0b00000000, A);   // Port A: all pins are INPUT
  myMCP.setPortMode(0b00000000, B);   // Port B: all pins are INPUT
  delay(wT);
  
  myMCP.setPortPullUp(0b11111111, A);  // pulled up
  myMCP.setPortPullUp(0b11111111, B);  // pulled up
}

void loop(){ 

  portStatusA = myMCP.getPort(A); // query the complete port status 
  portStatusB = myMCP.getPort(B); // query the complete port status 

  Serial.print(portStatusA, BIN);
  Serial.print(" ");
  Serial.print(portStatusB, BIN);
  Serial.println("");
 
  delay(100);
} 
```

**Comment by wollewald** [comment]
I just tried your sketch without any changes. My board was an Arduino Nano. I connected all GPIOs of the MCP23S17 to LOW (GND) except A6, which was connected to HIGH (VCC). That should be the same like you did. By the way, "01000000 00000000" would mean that A6 is HIGH and not A7.

My result is as expected:

![Screenshot 2023-10-29 013823](https://github.com/wollewald/MCP23017_WE/assets/41305162/8972e5bc-9fc2-4808-bd0e-b86c06e69d34)

And it also works with A7 HIGH and the rest LOW. So, I can't reproduce the issue. 

At least with an MCP23**S**17 it should also work on your side. For the MCP23**0**17 there is one known issue with GPIOA7 and B7. Microchip has changed the design and as a result these pins can only be used as outputs.

Not sure what else I can say or do. Maybe you can provide some more details of your microcontroller and the circuit?

**Comment by dev-markus** [comment]
Hello wollewald,
thanks for your quick reply and test!

Here is more information regarding the circuit diagram, Chip and Serial Output.

Problem description:
At the moment when one of the two pins (GPA7 or GPB7) are connected, a "0" is removed from the output. When it set to high, the full number (16) will show. See on the image. This behavior does not appear with the other pins. Therefore difficult to deal with since we need all the 128bit inputs with 8 chips :-)

We have try first the MCP23**0**17 and had the problem with the two pins and have think its the chip input problem. So we order the MCP23**S**17 and there have the same behavior.

Could the wiring be wrong or the code reading of the 16 bit inputs?

Order MCP23S17: https://www.reichelt.at/at/de/bus-controller-push-pull-s-dil-28-mcp-23s17-e-sp-p90047.html?&trstct=pos_0&nbc=1

Circuit, Chip, Serial Output:
![Unbenannt](https://github.com/wollewald/MCP23017_WE/assets/34211377/76bb0720-1c9e-402a-9b95-ebf15f26f9e7)

**Comment by wollewald** [comment]
Preceding zeros are not displayed, i.e.:  0b01111111 = 0b1111111. So, if you push the button connected to at GPA7 you should get:

1111111 11111111  or if you print in decimal numbers: 127 255 or in hex: 0x7F 0xFF

Did you expect:

01111111 11111111 ? 

Or did you expect:

11111110 11111111 ? 

The latter is what you get if you pull GPA0 to LOW.

**Comment by dev-markus** [comment]
would have imagined i get: "01111111 11111111".
in this case the mystery has been solved, chips are working correctly :-)
Thank you for your time!

**Comment by wollewald** [comment]
Great! Happy to hear that. 

And it had a good side effect because while working on the issue I have noticed that I had a typo in one of the file names of the examples sketches. And therefore it was not displayed as example in the Arduino IDE.
