### ISSUE TITLE
How to change I2C address

### ISSUE THREAD

**Issue by thijstriemstra** [wollewald/MCP23017_WE#5]
hi @wollewald I have one of these mcp23017 devices:

![IMG_1531](https://user-images.githubusercontent.com/305679/95356929-8488bd00-08c7-11eb-86ff-e388480c62c8.JPG)

and the address 0x20 shows up. I want to add another one and change the address to let's say 0x21. Any idea what I need to do with these A0, A1, A2 jumpers?

**Comment by wollewald** [comment]
Hi @thijstriemstra, the address scheme is in binary number: 1 0 0 A2 A1 A0. If Ax (with x = 0, 1, 2) is connected to GND replace Ax it by zero, if connected to VCC replace it by one. On the photo all Ax are connected to GND, so the address is 100000 = 0x20. Connect A0 to VCC and leave the rest as is and you'll get the address 100001 = 0x21. --> and so on...
So for 0x21 solder out the SMD resistor and connect the middle pad with VCC. The resistor is 0 Ohm, so you can also connect it with a drop of  tin-solder.

**Comment by thijstriemstra** [comment]
Awesome, thanks for the confirmation, I'll give it a try.

**Comment by thijstriemstra** [comment]
ps. i couldn't find it in your article, maybe useful to add that info there as well.

**Comment by thijstriemstra** [comment]
```
Scanning...
I2C device found at address 0x21  !
done
```

thx!
